<div class="panel panel-default">
    <div class="panel-heading"><h1><strong>Limpar Base</strong></h1></div>
    <div class="panel panel-body">
        <h5>
            <button type="button" class="btn btn-info" onclick="fVoltar();"> Voltar </button>
        </h5>
        <div>
            <p>Serão excluídos os arquivos XML com data inferior a <?php echo $this->anomes; ?>.</p>
            <?php if (empty($this->mensagem)) { ?>
            <br /><br /><br /><br /><br />
            <form name="myform" method="post" action="<?php echo APPLICATION_DIR; ?>/admin/limparbase">
                 <button type="submit" class="btn btn-primary"> Confirma a Exclusão dos Arquivos </button>
            </form>
            <?php } ?>
            <p><?php echo $this->mensagem; ?></p>
        </div>
    </div>
</div>
<script type="text/javascript">
    function fVoltar() {
        location = "<?php echo APPLICATION_DIR; ?>";
    }
</script>