<?php
if ($this->clientesxmlData['ativo'] == 1) {
    $ativo = "checked";
} else {
    $ativo = "";
}
?>
<div class="panel panel-default">
    <div class="panel-heading"><h1><strong>Cadastro de Clientes XML</strong></h1></div>
    <div class="panel panel-body">
        <button type="button" class="btn btn-info" onclick="javascript:fVoltar();"> Voltar </button>
        <button type="button" class="btn btn-primary" onclick="javascript:fInserir(0);"> Inserir Cliente XML </button>
        <?php if ($this->id <> 0) { ?>
            <button type="button" class="btn btn-danger"  onclick="javascript:fExcluir(<?php echo $this->id; ?>);"> Excluir Cliente XML</button>
        <?php } ?>
        <hr>
        <?php
        if (!empty($this->errorMsg)) {
            echo $this->errorMsg . "<br><br>";
        }
        ?>
        <form class="form-horizontal" role="form" action="<?php echo APPLICATION_DIR; ?>/clientesxml/cad/id/<?php echo $this->id; ?>" method="post">
            <!-- identificacao -->
            <div class="form-group" form-group-lg>
                <label for="Identificação" class="col-sm-2 controllabel text-right">Identificação</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="identificacao" placeholder="Identificação" maxlength="45" required value="<?php echo $this->clientesxmlData['identificacao']; ?>">
                </div>
            </div>
            <!-- url -->
            <div class="form-group" form-group-lg>
                <label for="url" class="col-sm-2 controllabel text-right">URL</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="url" placeholder="URL" maxlength="120" required value="<?php echo $this->clientesxmlData['url']; ?>">
                </div>
            </div>
            <!-- Tipo -->
            <div class="form-group" form-group-lg>
                <label for="url" class="col-sm-2 controllabel text-right">Tipo</label>
                <div class="col-sm-10">
                    <select name="tipo" class="form-control" >
                        <?php
                        foreach ($this->tipo as $d) {
                            if ($d["id"] == $this->mytipo) {
                                $text = 'selected="yes"';
                            } else {
                                $text = "";
                            }
                            echo "<option " . $text . " value='" . $d["id"] . "'>" . $d["descri"] . "</option>";
                        }
                        ?>
                    </select>
                </div>
            </div>
            <!-- Pista -->
            <div class="form-group" form-group-lg>
                <label for="url" class="col-sm-2 controllabel text-right">Pista</label>
                <div class="col-sm-10">
                    <select name="pista"   class="form-control" >
                        <?php
                        foreach ($this->pista as $d) {
                            if ($d["id"] == $this->mypista) {
                                $text = 'selected="yes"';
                            } else {
                                $text = "";
                            }
                            echo "<option " . $text . " value='" . $d["id"] . "'>" . $d["descri"] . "</option>";
                        }
                        ?>
                    </select>
                </div>
            </div>
            <!-- ativo -->
            <div class="form-group" form-group-sm>
                <label for="ativo" class="col-sm-2 controllabel text-right">Ativo</label>
                <div class="col-sm-1">
                    <input type="checkbox" class="form-control" name="ativo"   <?php echo $ativo; ?>>
                </div>
            </div>
            <!-- Salvar -->
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-4">
                    <button type="submit" class="btn btn-primary"> Salvar </button>
                    <input type="hidden" name="<?php echo $this->fieldName; ?>" value="<?php echo $this->token; ?>">
                </div>
            </div>
        </form>
    </div>
</div>

<script type="text/javascript">
    function fVoltar() {
        location = "<?php echo APPLICATION_DIR; ?>/clientesxml";
    }
    function fInserir(id) {
        location = "<?php echo APPLICATION_DIR; ?>/clientesxml/cad/id/" + id;
    }
    function fExcluir(id) {
        var salvar = confirm("Confirma Excluir Cliente?");
        if (salvar == 1) {
            location = "<?php echo APPLICATION_DIR; ?>/clientesxml/excluir/id/" + id;
        }
    }
</script>