<!--
// cadastro de Clientes XML
// ClientesxmlController.php
-->
<div class="panel panel-default">
    <div class="panel-heading"><h1><strong>Clientes XML</strong></h1></div>
    <div class="panel panel-body">
        <h5>
            <button type="button" class="btn btn-info" onclick="fVoltar();"> Voltar </button>
            <button type="button" class="btn btn-primary" onclick="fInserir(0);"> Inserir Cliente XML</button>
        </h5>
        <div>
            <table id="mytab" class="display" width='100%'>
                <thead>    
                    <tr>
                        <th>Identificação</th>
                        <th>URL</th>
                        <th>Pista</th>
                        <th>Tipo</th>
                        <th>Ativo</th>
                        <th>&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    $cont = 0;
                    foreach ($this->clientesxmlData as $d) {
                        ?>
                        <tr>
                <td><?php echo $this->escape($d['identificacao']) ?></td>
                <td><?php echo $d['url'] ?></td>
                <td><?php echo $d['pista'] ?></td>
                <td><?php echo $d['tipo'] ?></td>
                <td><?php
                    if ($d['ativo'] == 1) {
                        echo 'Sim';
                    } else {
                        echo 'Não';
                    }
                    ?></td>
                <td>
                    <a href="#" onclick="fInserir(<?php echo $d['idclientesxml']; ?>)" title="Editar"><img src="<?php echo APP_IMAGES; ?>/edit.png"></a>&nbsp;&nbsp;
                 </td>
            </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('#mytab').DataTable(
                {
                    "order": [[1, "asc"], [2, "asc"]],
                    "lengthMenu": [[25, 50, 100, -1], [25, 50, 100, "Todas"]],
                    language: {
                        "sEmptyTable": "Nenhum registro encontrado",
                        "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                        "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
                        "sInfoFiltered": "(Filtrados de _MAX_ registros)",
                        "sInfoPostFix": "",
                        "sInfoThousands": ".",
                        "sLengthMenu": "_MENU_ resultados por página",
                        "sLoadingRecords": "Carregando...",
                        "sProcessing": "Processando...",
                        "sZeroRecords": "Nenhum registro encontrado",
                        "sSearch": "Pesquisar ",
                        "oPaginate": {
                            "sNext": " Próximo",
                            "sPrevious": "Anterior ",
                            "sFirst": "Primeiro",
                            "sLast": "Último"
                        },
                        "oAria": {
                            "sSortAscending": ": Ordenar colunas de forma ascendente",
                            "sSortDescending": ": Ordenar colunas de forma descendente"
                        }
                    }
                }
        );
    });

    function fVoltar() {
        location = "<?php echo APPLICATION_DIR; ?>";
    }
    function fInserir(id) {
        location = "<?php echo APPLICATION_DIR; ?>/clientesxml/cad/id/" + id;
    }
</script>
