<!--
// visualização do Histórico de Aletas
// HistoricoController
-->
<div class="panel panel-default">
    <div class="panel-heading"><h1><strong>Histórico de Alertas</strong></h1></div>
    <div class="panel panel-body">
        <h5>
            <button type="button" class="btn btn-info" onclick="fVoltar();"> Voltar </button>
        </h5>
        <div>
            <form name="myform" method="post" action="<?php echo APPLICATION_DIR; ?>/historico/alertas">
                <table class="tableForm" style="width:100%;">
                    <tr>
                        <td class="td1Form" style="width:140px;text-align:right;">
                            <label for="dt1">Período&nbsp;</label>
                            <input  type="text" name="dt1" id="dt1" class="tcal" style="width: 100px;" value="<?php echo $this->dt1 ?>"/>
                            <input  type="text" name="dt2" id="dt2"  class="tcal" style="width: 100px;" value="<?php echo $this->dt2 ?>"/>
                            <label for="dt1">Pista&nbsp;</label>
                            <select name="pista">
                                <option>TODAS</option>
                                <option>09</option>
                                <option>27</option>
                            </select>
                            <input type="button" id="btnSalvar" onclick="fsalvar();" value="Filtrar">
                        </td>
                    </tr>
                </table>
            </form>
            <?php if (!empty($this->data)) { ?>
                <table id="mytab" class="display" width='100%'>
                    <thead>    
                        <tr>
                            <th>Data/Hora</th>
                            <th>Pista</th>
                            <th>VelC</th>
                            <th>VelP</th>
                            <th>VelTE</th>
                            <th>VelTD</th>
                            <th>VarC</th>
                            <th>VarP</th>
                            <th>VarTD</th>
                            <th>VarTE</th>
                            <th>Windshear</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($this->data as $d) {
                            $style1 = "";
                            $style2 = "";
                            $style3 = "";
                            $style4 = "";
                            $style5 = "";
                            $style6 = "";
                            $style7 = "";
                            $style8 = "";
                            $style9 = "";
                            $date = new Zend_Date($d['datahora']);
                            $mydata = $date->toString("dd/MM/yyyy HH:mm");
                            if ($d['alertavelcauda']) {
                                $style1 = "  bgcolor='yellow'";
                            }
                            if ($d['alertavelproa']) {
                                $style2 = "  bgcolor='yellow'";
                            }
                            if ($d['alertavelte']) {
                                $style3 = "  bgcolor='yellow'";
                            }
                            if ($d['alertaveltd']) {
                                $style4 = "  bgcolor='yellow'";
                            }
                            if ($d['alertavc']) {
                                $style5 = "  bgcolor='yellow'";
                            }
                            if ($d['alertavp']) {
                                $style6 = "  bgcolor='yellow'";
                            }
                            if ($d['alertavte']) {
                                $style7 = "  bgcolor='yellow'";
                            }
                            if ($d['alertavtd']) {
                                $style8 = "  bgcolor='yellow'";
                            }
                            if ($d['alertaw']) {
                                $style9 = "  bgcolor='yellow'";
                            }
                            ?>
                            <tr>
                                <td><?php echo $this->escape($mydata) ?></td>
                                <td><?php echo $this->escape($d['pista']) ?></td>
                                <td <?php echo $style1; ?>><?php echo $this->escape($d['velocidadecauda']) ?></td>                                
                                <td <?php echo $style2; ?>><?php echo $this->escape($d['velocidadeproa']) ?></td>
                                <td <?php echo $style3; ?>><?php echo $this->escape($d['velocidadetravesesquerdo']) ?></td>
                                <td <?php echo $style4; ?>><?php echo $this->escape($d['velocidadetravesdireito']) ?></td>
                                <td <?php echo $style5; ?>><?php echo $this->escape($d['variacaocauda']) ?></td>
                                <td <?php echo $style6; ?>><?php echo $this->escape($d['variacaoproa']) ?></td>
                                <td <?php echo $style7; ?>><?php echo $this->escape($d['variacaotravesesq']) ?></td>
                                <td <?php echo $style8; ?>><?php echo $this->escape($d['variacaotravesdir']) ?></td>
                                <td <?php echo $style9; ?>><?php echo $d['windshear'] ?></td>
                            </tr>
                        <?php } ?>
                    </tbody>
                    </tbody>
                </table>
                <br>
                <p>Limite de 2000 registros exibidos.</p>
                <?php
            } else {
                echo "Não foram encontrados registros.";
            }
            ?>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('#mytab').DataTable(
                {
                    "order": [[0, "desc"]],
                    "lengthMenu": [[25, 50, 100, -1], [25, 50, 100, "Todas"]],
                    language: {
                        "sEmptyTable": "Nenhum registro encontrado",
                        "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                        "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
                        "sInfoFiltered": "(Filtrados de _MAX_ registros)",
                        "sInfoPostFix": "",
                        "sInfoThousands": ".",
                        "sLengthMenu": "_MENU_ resultados por página",
                        "sLoadingRecords": "Carregando...",
                        "sProcessing": "Processando...",
                        "sZeroRecords": "Nenhum registro encontrado",
                        "sSearch": "Pesquisar ",
                        "oPaginate": {
                            "sNext": " Próximo",
                            "sPrevious": "Anterior ",
                            "sFirst": "Primeiro",
                            "sLast": "Último"
                        },
                        "oAria": {
                            "sSortAscending": ": Ordenar colunas de forma ascendente",
                            "sSortDescending": ": Ordenar colunas de forma descendente"
                        }
                    }
                }
        );
    });

    function fVoltar() {
        location = "<?php echo APPLICATION_DIR; ?>";
    }
    function fsalvar() {
        if (!isDate(document.getElementById('dt1').value)) {
            alert("Por favor, preencha o valor correto no campo [Data de Início].");
            document.forms["myform"].dt1.focus();
            return;
        }
        if (!isDate(document.getElementById('dt2').value)) {
            alert("Por favor, preencha o valor correto no campo [Data de Fim].");
            document.forms["myform"].dt2.focus();
            return;
        }
        document.forms["myform"].submit();
    }

</script>