<div class="panel panel-default">
    <div class="panel-heading"><h1><strong>Serviços Disponibilizados pelo SDPVA</strong></h1></div>
    <div class="panel panel-body">
        <h5>
            <button type="button" class="btn btn-info" onclick="fVoltar();"> Voltar </button>
        </h5>
        <br />
        <p>Para maiores informaçoes consulte o <a href="/SDPVA/public/downloads/Manual_do_Usuario_SDPVA.pdf" download target="_blank">Manual do Usuario SDPVA</a>.</p>
        <br />
        <table class="table">
            <thead>
            <tr>
                <th class="thcenter">Serviço</th>
                <th class="thcenter">Descrição</th>
                <th class="thcenter">Parâmetros</th>
                <th class="thcenter">Exemplo</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><strong>getdiagnostico</strong></td>
                <td>Solicitar XML do diagnóstico.<br>Os parâmetros são opcionais. Quando não especificados os valores padrão são: dt - data/hora atual; pista - 09 e local SBGR.</td>
                <td>Data (dt), Pista (pista) e Local (local)</td>
                <td>https://[domínio ou IP]/SDPVA/services/getdiagnostico/dt/YYYYMMDD/pista/09/local/SBGR></td>
            </tr>
            <tr>
                <td><strong>getalertas</strong></td>
                <td>Solicitar XML dos alertas.<br>Os parâmetros são opcionais. Quando não especificados os valores padrão são: dt - data/hora atual; pista - 09 e local SBGR.</td>
                <td>Data (dt), Pista (pista) e Local (local)</td>
                <td>https://[domínio ou IP]/SDPVA/services/getalertas/dt/YYYYMMDD/pista/09/local/SBGR></td>
            </tr>
            <tr>
                <td><strong>getgeral</strong></td>
                <td>Solicitar XML geral.<br>O XML Geral permite remontar os dados para processamento do SDPVA. Os parâmetros são opcionais. Quando não especificados os valores padrão são: dt - data/hora atual e local SBGR.</td>
                <td>Data (dt) e Local (local)</td>
                <td>https://[domínio ou IP]/SDPVA/services/getgeral/dt/YYYYMMDD/local/SBGR></td>
            </tr>
            <tr>
                <td><strong>getprognostico</strong></td>
                <td>Solicitar XML do prognostico.<br>Os parâmetros são opcionais. Quando não especificados os valores padrão são: dt - data/hora atual e local SBGR.</td>
                <td>Data (dt) e Local (local)</td>
                <td>https://[domínio ou IP]/SDPVA/services/getprognostico/dt/YYYYMMDD/local/SBGR></td>
            </tr>
            <tr>
                <td><strong>getmnd</strong></td>
                <td>Solicitar arquivo MND gerado pelo SODAR.<br>Os parâmetros são opcionais. Quando não especificados os valores padrão são: dt - data do último arquivo gerado e local SBGR.</td>
                <td>Data do arquivo (dt) e Local (local)</td>
                <td>https://[domínio ou IP]/SDPVA/services/getmnd/dt/YYMMDD/local/SBGR></td>
            </tr>
        </table>
    </div>
</div>
<script type="text/javascript">
        function fVoltar() {
        location = "<?php echo APPLICATION_DIR; ?>";
    }
</script>